# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('c', 'CONSUMPTION'), ('a', 'ACTIVITY')], max_length=1)),
                ('what', models.CharField(max_length=100)),
                ('when', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('i', 'INTAKE'), ('o', 'OUTTAKE')], max_length=1)),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('totalCalorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(max_length=50)),
                ('nutrients', models.TextField(default='{}')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Recipe')),
            ],
        ),
    ]
