# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20161101_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('fc', 'FOOD_CONSUMPTION'), ('rc', 'FOOD_CONSUMPTION'), ('a', 'ACTIVITY')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='what',
            field=models.CharField(max_length=255),
        ),
    ]
