# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20161114_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ndbno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('fc', 'FOOD_CONSUMPTION'), ('rc', 'RECIPE_CONSUMPTION'), ('a', 'PHYSICAL_ACTIVITY')], max_length=1),
        ),
    ]
