# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0007_auto_20161114_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('height', models.SmallIntegerField()),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('fc', 'food_consumption'), ('rc', 'recipe consumption'), ('a', 'physical activity')], max_length=1),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='category',
            field=models.CharField(choices=[('i', 'i'), ('o', 'o')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='totalCalorie',
            field=models.IntegerField(default=0),
        ),
    ]
