# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_userweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='totalCalorie',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
